trigger:
  - main # Or whichever branch you use for releases

variables:
  dockerRegistryServiceConnection: 'dockerhub_connection' # This service connection is for the build stage to push to Docker Hub
  imageRepository: 'dmoayad/authentication_app_frontend' # Name of your Docker image on Docker Hub
  dockerFilePath: '$(Build.SourcesDirectory)/Dockerfile' # Path to your Dockerfile
  tag: '$(Build.BuildId)'
  vmUsername: 'moayad'
  ssh-connection: 'jumphost-vm-connection'
  jumpHostIP: '13.86.93.117'
  frontendVm1PrivateIP: '10.0.2.4'
  frontendVm2PrivateIP: '10.0.2.5'
  sshKeySecureFile: 'key.pem' # Upload your SSH private key as a Secure File in Azure DevOps

stages:
  # - stage: BuildAndPush
  #   displayName: Build and push Docker image to Docker Hub
  #   jobs:
  #     - job: BuildPush
  #       displayName: Build and Push to Docker Hub
  #       pool:
  #         vmImage: 'ubuntu-latest' # Or your preferred agent image

  #       steps:
  #         - task: Docker@2
  #           displayName: Build and push an image to Docker Hub
  #           inputs:
  #             containerRegistry: '$(dockerRegistryServiceConnection)' # Use your Docker Hub Service Connection
  #             repository: '$(imageRepository)'
  #             command: 'buildAndPush'
  #             Dockerfile: '$(dockerFilePath)'
  #             tags: '$(tag)'

  - stage: DeployFrontend
    displayName: Deploy to Frontend VMs
    jobs:
      - deployment: DeployToFrontend
        displayName: Deploy Web App
        environment: 'production-frontend' # Or a suitable environment name
        strategy:
          runOnce:
            deploy:
              steps:
                # You may still need to install the SSH key if your jumphost requires it
                # based on the SSH Service Connection configuration.
                # - task: InstallSSHKey@0
                #   displayName: Install SSH Key
                #   inputs:
                #     knownHostsEntry: |
                #       # Add the public key of your jumphost here
                #       # Example: [jumphost.eastus.cloudapp.azure.com]:22 ssh-rsa AAAA...
                #     sshPublicKey: '' # Leave empty if using a secure file for the private key
                #     sshKeySecureFile: '$(sshKeySecureFile)'

                # Deploy to Frontend VM 1 via Jumphost
                # - task: Bash@3
                #   displayName: List files in source directory
                #   inputs:
                #     targetType: 'inline'
                #     script: 'ls -l $(Build.SourcesDirectory)'
                - task: SSH@0
                  displayName: Deploy to Frontend VM 1
                  inputs:
                    sshEndpoint: '$(ssh-connection)'
                    runOptions: 'script'
                    scriptPath: '$(Build.SourcesDirectory)/deploy_frontend.sh' # Use full path
                    arguments: '"$(vmUsername)" "$(frontendVm1PrivateIP)" "$(imageRepository)" "latest"'
                # # Deploy to Frontend VM 2 via Jumphost
                # - task: SSH@0
                #   displayName: Deploy to Frontend VM 2
                #   inputs:
                #     sshEndpoint: '$(ssh-connection)' # Reuse the SSH Service Connection to your Jumphost
                #     runOptions: 'script' # Use 'script' option
                #     scriptPath: '$(Build.SourcesDirectory)/deploy_frontend.sh' # Path to your deployment script
                #     arguments: '"$(vmUsername)" "$(frontendVm2PrivateIP)" "$(imageRepository)" "$(tag)"' # Pass variables as arguments (ACR name removed)
